name: EquiNation
version: '${project.version}'
main: me.quartz.equination.EquiNation
api-version: '1.20'
commands:
  addowner:
  addtrust:
  delowner:
  deltrust:
  hage:
  hbreed:
  hhealth:
  hheight:
  hid:
  hspawn:
  htame: